### PR TITLE
Typhoeus was applying blacklisted domains wrong

### PR DESCRIPTION
**Pull request by Qard**
Looks like the domain blacklisting in typhoeus was backwards. This fixes it.

@pglombardo Can you review this? Particularly the tests. I imagine there's probably a better way to write that test. I'm not used to this codebase though. :)

### CODE REVIEW

**Comment by pglombardo** [comment]
@qard the tests look great.  I like how you tested the xtrace edges.  We should do that more in Ruby.

But for the actual change, I don't think that line is need at all actually.  On [line 18](https://github.com/appneta/oboe-ruby/blob/typhoeus-fix/lib/oboe/inst/typhoeus.rb#L18) we conditionally set an xtrace header in the outgoing request, run the request on [line 20](https://github.com/appneta/oboe-ruby/blob/typhoeus-fix/lib/oboe/inst/typhoeus.rb#L20) which saves the response in `response`, and then on the line you modified we attempt to assign the x-trace header in the response (which doesn't make sense).

I think that line should actually be deleted entirely.  Not sure why I had it there in the first place...

Then for picking up the response context, we conditionally do that in the `unless blacklisted` block on [line 46](https://github.com/appneta/oboe-ruby/blob/typhoeus-fix/lib/oboe/inst/typhoeus.rb#L46).

Thoughts?  It's a great find in any case.

**Comment by Qard** [comment]
It seems like it is intended to prevent particular servers from continuing a trace. Not sure why we'd be doing that, but it seems to be part of an actual feature--node doesn't have this.

Line 18 would prevent the remote server from continuing the trace from the server making the request. But the remote server would still set the X-Trace header on the response. Upon returning to the client server, the trace would try to link back to the exit from the new trace on the remote server and you'd end up with two broken traces.

**Comment by pglombardo** [comment]
I believe @dankosaur originally made the request to add a blacklist.  At one point we had one customer  that used the services of another (swipely?) and TV would show both linked traces to the user even though one belonged to another account.  This was a way to block that.

In any case, we only do the context linking if blacklist is false (both before and after the request).

**Comment by dankosaur** [comment]
Yes, this isn't a common issue yet, but we have run into cases where
requests trace across multiple customers. This yields broken traces on both
sides, as we don't associate the two parts but do see missing events from
each.

The blacklist is not our ideal solution and was implemented in ruby
originally for a prospect "upaknee". It may have factored in for swipely as
well. We don't have this capability in other languages and if we start
seeing more demand for a solution we will probably go with a more automatic
systemic change that's already been designed. More discussion in
https://github.com/tracelytics/oboe/issues/148

**Comment by Qard** [comment]
Ah, I would've assumed the collector would just spot the cross-linking and do something about it there. I didn't realize it was actually an issue having a trace from one customer linking into a trace from another.

So should this just be left as it is until we fix the issue in liboboe?

**Comment by pglombardo** [comment]
[Line 31](https://github.com/appneta/oboe-ruby/blob/typhoeus-fix/lib/oboe/inst/typhoeus.rb#L31-L33) is what was causing the broken edge (TVI-1497) because it's incorrectly modifying the response with a context we already have.  I would just delete those 3 lines entirely.

Re: missing service keys - I think that's because we lost the info event in that broken trace.  The service keys and a backtrace is [recorded here](https://github.com/appneta/oboe-ruby/blob/typhoeus-fix/lib/oboe/inst/typhoeus.rb#L27-L42).  We even validate those service keys and the existence of a backtrace in [the tests](https://github.com/appneta/oboe-ruby/blob/typhoeus-fix/test/instrumentation/typhoeus_test.rb#L35).

**Comment by MikeA-** [comment]
@pglombardo - Stephen said he is done with this, so please review and merge at your leisure.  Thanks @Qard !

**Comment by pglombardo** [comment]
This has been released in [gem 2.7.9.6](https://github.com/appneta/oboe-ruby/releases/tag/rel-2.7.9.6).

**Pull request merged**
